### ISSUE TITLE
Issue with the license

### ISSUE THREAD

**Issue by umgefahren** [AlexiaChen/mpvss-rs#4]
Hey!
I really like what you did there and I'm considering building upon it. Although I'm probably unable tu make use of your library, because of the license you put it under. Unfortunately GPLv3 has a strong [Copyleft](https://en.wikipedia.org/wiki/Copyleft) which would mandate me to put my project under the same license. I want to be very clear: My project will be Open Source as well, but I want to make closed source adaptions possible (this is important for broad adoption). If you want to keep all changes here (although this is not legal council), you could consider changing to [GPL with linking exception](https://en.wikipedia.org/wiki/GPL_linking_exception). 
I will, of course, respect all decisions regarding your choice of license, I just thought you might want to know.
Best of wishes. Your work is amazing and there are only a few secret sharing libraries for Rust, so I really appreciate your work.

**Comment by AlexiaChen** [comment]
Hey @umgefahren !

Thank you for your appreciation, what can I do to help you?  add GPL with linking exception ? How can I add this statement to my project? Also, if you find any problems or bugs using my library, feel free to fix the bugs or improve the performance of this library by pull request, because the performance of this library is not ideal at the moment, without using the underlying computing libraries like libgmp

**Comment by charleschege** [comment]
But it seems like there are no GPL licensed libraries in this repo? Where do you use libgmp?

**Comment by charleschege** [comment]
I would ask you to license this library in a more permissive license. This would be beneficial for the rust ecosystem. And your library is really well done, it could go a long way to improving our rust ecosystem for open source and commercial applications

**Comment by AlexiaChen** [comment]
OK. I can change it to MIT license if you want（now its GPLv3）. it does not use libgmp.  feel free to contribute it by create PR

**Comment by charleschege** [comment]
MIT would be great

**Comment by charleschege** [comment]
MIT would be great

**Comment by charleschege** [comment]
https://github.com/AlexiaChen/mpvss-rs/pull/5 solves the license issue

**Comment by charleschege** [comment]
Is it possible to release a new version on crates.io with this license at this time?

**Comment by AlexiaChen** [comment]
@charleschege   sure

**Comment by AlexiaChen** [comment]
@charleschege Github action failed: https://github.com/AlexiaChen/mpvss-rs/runs/3066841187

**Comment by AlexiaChen** [comment]
@charleschege    published new version to crates.io, please check it

**Comment by charleschege** [comment]
Thanks
